import typography from '@tailwindcss/typography';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./src/**/*.{html,njk,md,js}",
  ],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Space Grotesk"', 'sans-serif'],
        mono: ['"Space Mono"', 'monospace'],
        pixel: ['"Space Mono"', 'monospace'],
      },
      boxShadow: {
        'brutal-xs': '2px 2px 0px 0px #000000',
        'brutal-sm': '3px 3px 0px 0px #000000',
        'brutal': '4px 4px 0px 0px #000000',
        'brutal-lg': '6px 6px 0px 0px #000000',
        'brutal-xl': '8px 8px 0px 0px #000000',
        'brutal-bottom': '0px 4px 0px 0px #000000',
        'brutal-amber': '4px 4px 0px 0px #f49a60',
        'brutal-cyan': '4px 4px 0px 0px #35a7ff',
        'brutal-yellow': '4px 4px 0px 0px #fde047',
        'brutal-mint': '4px 4px 0px 0px #86efac',
      },
      keyframes: {
        ticker: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        },
        spin_slow: {
          '0%': { transform: 'rotate(0deg)' },
          '100%': { transform: 'rotate(360deg)' },
        },
        wiggle: {
          '0%, 100%': { transform: 'rotate(-2deg)' },
          '50%': { transform: 'rotate(2deg)' },
        },
        bounce_subtle: {
          '0%, 100%': { transform: 'translateY(0)' },
          '50%': { transform: 'translateY(-4px)' },
        },
      },
      animation: {
        ticker: 'ticker 22s linear infinite',
        tickerFast: 'ticker 14s linear infinite',
        spinSlow: 'spin_slow 10s linear infinite',
        wiggle: 'wiggle 2s ease-in-out infinite',
        bounceSubtle: 'bounce_subtle 2s ease-in-out infinite',
      },
      colors: {
        retro: {
          bg: "#fcf6e8",
          darkBg: "#12151e",
          card: "#fffdf9",
          cardDark: "#1a1e2b",
          ink: "#14161f",
          border: "#14161f",
          yellow: "#fde047",
          amber: "#f59e0b",
          peach: "#fb923c",
          mint: "#86efac",
          cyan: "#38bdf8",
          blue: "#3b82f6",
          lavender: "#c4b5fd",
          pink: "#f472b6",
          red: "#f87171",
          cream: "#fbf3de",
        },
        night: {
          DEFAULT: "#080b12",
          100: "#030508",
          200: "#05080e",
          300: "#080b12",
          400: "#0e1322",
          500: "#151c30",
          600: "#222d4a",
          700: "#3b4b74",
          800: "#6579a8",
          900: "#a8b8db",
        },
        cream: {
          DEFAULT: "#f5ede3",
          muted: "#a69e94",
          faint: "#5c564f",
        },
        amber_glow: {
          DEFAULT: "#f49a60",
          light: "#ffd4a3",
          dark: "#ce784e",
        },
        catppuccin: {
          rosewater: "#f5e0dc",
          flamingo: "#f2cdcd",
          pink: "#f5c2e7",
          mauve: "#cba6f7",
          red: "#f38ba8",
          maroon: "#eba0ac",
          peach: "#fab387",
          yellow: "#f9e2af",
          green: "#a6e3a1",
          teal: "#94e2d5",
          sky: "#89dceb",
          sapphire: "#74c7ec",
          blue: "#89b4fa",
          lavender: "#b4befe",
          text: "#cdd6f4",
          subtext1: "#bac2de",
          subtext0: "#a6adc8",
          overlay2: "#9399b2",
          overlay1: "#7f849c",
          overlay0: "#6c7086",
          surface2: "#585b70",
          surface1: "#45475a",
          surface0: "#313244",
          base: "#1e1e2e",
          mantle: "#181825",
          crust: "#11111b",
        },
        reading: {
          bg: "#1e1e2e",
          surface: "#181825",
          elevated: "#11111b",
          border: "#313244",
          subtle: "#45475a",
          muted: "#a6adc8",
          faint: "#6c7086",
          text: "#cdd6f4",
          heading: "#cdd6f4",
          link: "#89b4fa",
          accent: "#b4befe",
        },
      },
    },
  },
  corePlugins: {
    preflight: false,
    backdropBrightness: false,
    backdropContrast: false,
    backdropGrayscale: false,
    backdropHueRotate: false,
    backdropInvert: false,
    backdropOpacity: false,
    backdropSaturate: false,
    backdropSepia: false,
    blur: false,
    brightness: false,
    contrast: false,
    dropShadow: false,
    grayscale: false,
    hueRotate: false,
    invert: false,
    saturate: false,
    sepia: false,
    touchAction: false,
    scrollSnapType: false,
    scrollSnapAlign: false,
    scrollSnapStop: false,
    fontVariantNumeric: false,
    tableLayout: false,
    borderCollapse: false,
    borderSpacing: false,
  },
  plugins: [typography],
};
